### ISSUE TITLE
Extension showing summary instead of passwords list

### ISSUE THREAD

**Issue by dlazzy** [Rabbit-Company/Passky-Browser-Extension#3]
Hello,

When opening the extension on Chrome, it show a summary instead of the passwords list.

**Expected behavior**
Show the passwords list like on the Android Application.

**Screenshot**
[Image](https://i.ibb.co/GWmTPCh/Selection-517.png)

Environment :
 - OS: Ubuntu 20.04
 - Browser: chrome
 - Version: Version 98.0.4758.80
 - Hosted on my server using Docker.

Thanks for your work!

**Comment by zigazajc007** [comment]
Hello,

Thanks for reporting this.

There has been a big Passky Server upgrade from v5.2.0 to v6.0.0.

If you are still using Passky Server on version v5.2.0, I would recommend you install a browser extension that is compatible with Passky Server v5.2.0. https://github.com/Rabbit-Company/Passky-Browser-Extension/releases/tag/v5.0.0

If you want to upgrade Passky Server to v6.0.0, make sure you export your passwords first, delete docker containers and also files inside a folder on where a database is stored (By default in /passky). Then you can deploy Passky Server again with the new docker-compose.yml file. After everything has been deployed you can create a new account and import all your passwords back.

Here is the announcement I have sent to our discord server and users that has an account on Public Passky Servers: 
```
Hello,

First, I would like to thank everyone for supporting Passky.

On 14th February we will perform a big update (v6.0.0) on all Public Passky Servers. (User interaction required)

This update includes:
- Database optimizations
- API optimizations
- New API endpoint called getStats
- Switch to Apache image
- and much more

This update also brings many privacy advantages:
- Usernames and Websites are now also encrypted
- As you already know, the IP address from anyone that connects to Passky Server is hashed and stored for only 1 day. In update v6.0.0, the hash of the same IP address will be different from the one created yesterday.

I have talked with a lot of database experts and in this update database structure has changed a lot.
This would bring much more performance improvements.

Because of some big changes listed above and privacy improvements, the upgrade won't be possible.
That's why all data from registered users will be deleted from all Public Passky Servers and version v6.0.0 will be installed.

For those who want to keep using Passky, make sure to Export all passwords (Remember that exported passwords are in plain text so keep this file safe for 1 day, until we update all Passky Servers)

After the update is completed you can create a new account and import all your passwords back. (Now we also have servers in the US, so choose the closest server to you for the lowest latency).

We are really sorry for rushing this update, but this most likely won't happen again. So it's better to perform this update as fast as possible, while we still have only a small amount of users on public Passky servers.

Best Regards,
Ziga from Rabbit Company LLC
```

If you don't know what Passky Server version you are using, you can check that by pasting your Passky Server IP / domain in a browser search bar with ?action=getInfo at the end.
Example: http://localhost:8080?action=getInfo

If you need any help with the upgrade feel free to contact me.

**Comment by zigazajc007** [comment]
Note that the first number in the version code determines the compatibility.
Examples:
```
Server | Client
v5.0.0  | v6.0.0 <- not compatible
v6.0.0  | v5.0.0 <- not compatible
v6.0.0  | v6.9.9 <- compatible
v6.9.9  | v6.0.0 <- compatible
```
Make sure your Passky Server and Passky Client (Website, Browser extension, Desktop application, Android application...) have the same first number in version code.

**Comment by dlazzy** [comment]
Thank you very much for your reply.
This is what I do to get my passwords export working (button was not working) in extension (chrome) : 

* Remove current Passky extension from Chrome
* Used release 5.0.0 of the extension from your link https://github.com/Rabbit-Company/Passky-Browser-Extension/releases/tag/v5.0.0
* Unzip, then in chrome load the unpacked extension
* Login to my server
* Export working

After that I followed your instructions on server : 
* Stopped containers with `docker-compose stop`
* Remove containers with `docker rm [container_id, ...]` and also images and volumes
* After that I struggle with steps so I removed the entire Passky folder :sweat_smile: 
* Followed instructions from <https://github.com/Rabbit-Company/Passky-Server#passky-containers>
* Checked new version with http://[ip]:8080/?action=getInfo and get 6.0.0

```
{"version":"v6.0.0","users":-1,"maxUsers":2,"passwords":-1,"maxPasswords":1000,"location":"FR","error":"0","info":"Successful"}
```

But when I sign up a new user the extension throw me an error : `Something went wrong while connecting to the database!` ? When I check the log for the database container I get this :

```
...
2022-02-15  8:18:34 3 [Warning] Access denied for user 'passky'@'172.18.0.3' (using password: YES)
```
I followed instructions from the GUI installer, don't work and also retry from scratch with the CLI installer.

Thanks for your help

**Comment by zigazajc007** [comment]
If you see in http://[ip]:8080/?action=getInfo users and passwords -1 that means API can't connect to the database.

You have probably deployed Passky Server first and then delete the entire Passky folder. Use "docker-compose down" to stop and remove all containers. Then remove the whole /passky folder where the database is located and redeploy Passky Server back with "docker-compose up -d"

Passky Server will only recreate the database and database user if the passky folder does not exist.

**Comment by dlazzy** [comment]
Thank you very much! I skipped the step of deleting the whole `/passky` folder... And now it's working after deleting it and rebuild the containers :smile: 

Keep the good work :tada: thank you

**Comment by zigazajc007** [comment]
Note that for future updates you would need to use the same database password and user. So you won't need to remove /passky folder or do anything else than just recreating new containers. The installer will only create ".env" file so you also don't need to run the installer every time there is an update.

Also, make sure to delete your exported file from v5.2.0 and rather use the Backup option for backing up your passwords as they would be encrypted and you can then store this file to any cloud provider as they won't be able to decrypt your passwords without your master password.
